#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# CHECK IF THE APP CAN BE INSTALLED
#=================================================

# Testing if ZeroTier is installed
yunohost app list | grep -q "id: zerotier" || ynh_die "ZeroTier is needed, but it is not installed. There is a package for that!"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#REMOVEME? ynh_nodejs_install
ynh_hide_warnings corepack enable && corepack prepare pnpm@latest --activate

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

# Prevent ERR_OSSL_EVP_UNSUPPORTED error
export NODE_OPTIONS=--openssl-legacy-provider

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

ynh_script_progression "Building the backend..."
pushd $install_dir/backend
	ynh_hide_warnings ynh_exec_as_app yarn install
popd

ynh_script_progression "Building the frontend..."
pushd $install_dir/frontend
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app yarn build
popd

chown $app: "$install_dir/frontend"
chown -R $app: "$install_dir/frontend/public"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="ZeroTier Controller Web UI"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Let's retrieve information on the ZeroTier installation
zt_token="$(</var/lib/zerotier-one/authtoken.secret)"
zt_addr="localhost:$(</var/lib/zerotier-one/zerotier-one.port)"

ynh_config_add --template="env" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
