#!/bin/bash



source /usr/share/yunohost/helpers

#=================================================
# CHECK IF THE APP CAN BE INSTALLED
#=================================================

# Testing if ZeroTier is installed
yunohost app list | grep -q "id: zerotier" || ynh_die "ZeroTier is needed, but it is not installed. Restore its backup first, otherwise there is a package for that, then perform a force-upgrade of ZeroUI."

#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling dependencies..."

#REMOVEME? ynh_nodejs_install

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown $app:www-data "$install_dir/frontend"
chown -R $app:www-data "$install_dir/frontend/public"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="ZeroTier Controller Web UI"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

# Typically you only have either $app or php-fpm but not both at the same time...
ynh_systemctl --service=$app --action="start" --log_path="systemd"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
